id: restart-with-after-execution
namespace: io.kestra.tests

tasks:
  - id: hello
    type: io.kestra.plugin.core.log.Log
    message: Hello World! ðŸš€

  - id: fail_randomly
    type: io.kestra.plugin.core.execution.Fail
    runIf: "{{taskrun.attemptsCount == 0}}"
    errorMessage: Bad value returned!

  - id: log
    type: io.kestra.plugin.core.log.Log
    message: should finish here

afterExecution:
  - id: end
    type: io.kestra.plugin.core.log.Log
    message: after execution!